### ISSUE TITLE
Compiling from tex file doesn't give the same layout

### ISSUE THREAD

**Issue by dillontkh** [jovyntls/cheatsheets#32]
When I compile the tex file locally for cs2040s finals, the layout looks different from the original one and doesn't fit on 2 pages anymore

Result:
![image](https://user-images.githubusercontent.com/40649376/233404271-b99f693c-f735-43ad-b1ed-f31e1f44ff97.png)

**Comment by jovyntls** [comment]
Hi @dillontkh, thanks for opening this issue :)

Could I check what you're using the compile the file?

**Comment by dillontkh** [comment]
im using the latex workshop extension on vscode

the command run is 

pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "[filepath]"

**Comment by jovyntls** [comment]
Hmm I'm not familiar with vscode and its latex extension - could you try this config? Here are the options I'm using which compiles to 2 pages:
```
compiler: latexmk
  engine: -pdf
  options:
    -verbose
    -file-line-error
    -synctex=1
    -interaction=nonstopmode
  callback: 1
  continuous: 1
  executable: latexmk
```

**Comment by dillontkh** [comment]
![image](https://user-images.githubusercontent.com/40649376/233795970-ddd93974-26c1-4906-b86c-c210e62e665b.png)
That didn't seem to make a difference
Do you have this warning as well?

I think the issue is that `\usepackage[scaled=0.92]{helvet}` is not being used. The output PDF when I commented it out is identical to when it's not commented

**Comment by jovyntls** [comment]
> that didn't seem to make a difference 
> do you have this warning as well?

Yup, it should still be able to compile

> im using the latex workshop extension on vscode
> 
> the command run is
> 
> pdflatex -synctex=1 -interaction=nonstopmode -file-line-error -recorder "[filepath]"

Running this command on the CLI gives a 2-page output. Just as a sanity check, does it work if you 
- ensure there are no changes to the source tex file
- run the command (e.g. `pdflatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "cs2040s-finals-cheatsheet.tex"`) directly on your CLI (not using vscode)?

**Comment by dillontkh** [comment]
Yep, on a fresh clone of the repo and running the command in CLI still gives me the same result. Could it be there's a font you have installed that I don't?

**Comment by dillontkh** [comment]
here's a video of the process from start to finish
https://youtu.be/wL95vQ5tOgk

[cs2040s-finals-cheatsheet.log](https://github.com/jovyntls/cheatsheets/files/11303356/cs2040s-finals-cheatsheet.log)

and here's the log file

**Comment by jovyntls** [comment]
Thanks for providing the log file! Looks like the difference is from different versions of TeX - the 2020 version (which I'm using) compiles to 2 pages, and your version compiles to 3 pages :)

**Comment by dillontkh** [comment]
dang ok that's the end of that mystery, thanks!

**Comment by dillontkh** [comment]
any chance you're able to update it to work with the 2023 version? :P

**Comment by jovyntls** [comment]
unfortunately not in the near future, but this is a good reminder for me to update my tex version 😛
