### ISSUE TITLE
Minor Errata in CS3223 Finals Cheatsheet

### ISSUE THREAD

**Issue by Devanshshah1309** [jovyntls/cheatsheets#34]
The definition of "covering index" should be changed from:

> if all attributes referenced in $Q$ are part of the key of $I$ 

to:

> if all attributes referenced in $Q$ are part of the key **or include columns** of $I$ 

But doing so results in exceeding the one-page limit - so, I'm not sure if you want to make this change + remove one line from somewhere/reduce the font size by a bit/something else, or ignore this altogethr.

P.S. your cheatsheets have been incredibly useful 🙏  thanks a lot for them!

**Comment by jovyntls** [comment]
Hey thanks for letting me know!

I'll look into this in a few days cos I don't have access to my laptop now :p

**Comment by jovyntls** [comment]
fixed in the most recent commit

thanks again @Devanshshah1309 for the bug report!
